---
- hosts: all
  gather_facts: no

  tasks:

    # Bootstrap Ansible itself
    - include: tasks/bootstrap.yml

- hosts: all

  vars_files:
    - vars/mappings.yml

  tasks:

    # Prepare the base environment
    - include: tasks/base.yml
    - include: tasks/compat.yml
    - include: tasks/user.yml

    # Install base packages
    - include: tasks/packages.yml
      vars:
        project: base

    # Install build dependencies for each project
    - include: tasks/packages.yml
      with_items:
        '{{ projects }}'
      loop_control:
        loop_var: project
      when:
        - projects is defined

    # Install packages needed for the Jenkins agent
    - include: tasks/packages.yml
      vars:
        project: jenkins
      when:
        - flavor == "jenkins"

    # Configure the Jenkins agent
    - include: tasks/jenkins.yml
      when:
        - flavor == 'jenkins'
