---
- hosts: all
  gather_facts: no

  tasks:

    # Bootstrap Ansible itself
    - include: tasks/bootstrap.yml

- hosts: all

  vars_files:
    - vars/mappings.yml

  tasks:

    # Prepare environment. None of the actions performed here might
    # depend on packages being installed
    - include: tasks/base.yml

    # Install base packages
    - include: tasks/packages.yml
      vars:
        project: base

    # Remove blacklisted packages
    - include: tasks/packages.yml
      vars:
        project: blacklist
        state: absent

    # Configure environment. Needs to happen after installing base packages
    - include: tasks/bootloader.yml
    - include: tasks/services.yml
    - include: tasks/compat.yml
    - include: tasks/users.yml

    # Install build dependencies for each project
    - include: tasks/packages.yml
      with_items:
        - libvirt
      loop_control:
        loop_var: project
      when:
        - projects is defined

    # Install packages needed for the Jenkins agent
    - include: tasks/packages.yml
      vars:
        project: jenkins
      when:
        - flavor == "jenkins"

    # Configure the Jenkins agent
    - include: tasks/jenkins.yml
      when:
        - flavor == 'jenkins'
