---
- name: 'Install packages'
  package:
    name: '{{ packages }}'
    state: present

- name: 'Remove packages'
  package:
    name: '{{ unwanted_packages }}'
    state: absent

- include: 'tasks/packages-language-specific.yml'
  vars:
    pm_command: '{{ pm.command }}'
    pm_packages: '{{ pm.packages }}'
    pm_name: '{{ pm.name }}'
  when: pm_packages != ''
  loop:
    - name: PyPi
      command: '{{ paths.pip3 }} install'
      packages: '{{ pypi_packages | default(None) }}'

    - name: CPAN
      command: 'cpanm --notest'
      packages: '{{ cpan_packages | default(None) }}'
  loop_control:
    loop_var: pm
