---
- name: Fetch repository metadata
  apt:
    update_cache: true
  when: os.name == 'Debian' or os.name == 'Ubuntu'

- name: Install packages needed for playbook tasks
  package:
    name: '{{ early_install_packages }}'
    state: present

- name: Update installed packages
  package:
    name: '*'
    state: latest
  when:
    - packaging.format == 'rpm'
    - not ( os.name == 'Fedora' and
            os.version == 'Rawhide' )

- name: Update installed packages
  package:
    name: fedora-gpg-keys
    state: latest
    disable_gpg_check: yes
  when:
    - os.name == 'Fedora'
    - os.version == 'Rawhide'

- name: Update installed packages
  command: '{{ packaging.command }} update --refresh --exclude "kernel*" -y'
  when:
    - os.name == 'Fedora'
    - os.version == 'Rawhide'

- name: Update installed packages
  command: '{{ packaging.command }} update --disablerepo="*" --enablerepo=fedora-rawhide-kernel-nodebug "kernel*" -y'
  when:
    - os.name == 'Fedora'
    - os.version == 'Rawhide'

- name: Update installed packages
  apt:
    upgrade: dist
    update_cache: yes
  when:
    - packaging.format == 'deb'

- name: Update installed packages
  shell: '{{ packaging.command }} update && {{ packaging.command }} upgrade -y'
  when:
    - packaging.format == 'pkg'

- name: Clean up packages after update
  command: '{{ packaging.command }} mark install "kernel*"'
  when:
    - os.name == 'Fedora'

- name: Clean up packages after update
  shell: '{{ packaging.command }} clean packages -y && {{ packaging.command }} autoremove -y'
  when:
    - packaging.format == 'rpm'
    - os.name != 'OpenSUSE'

- name: Clean up packages after update
  shell: '{{ packaging.command }} clean'
  when:
    - os.name == 'OpenSUSE'

- name: Clean up packages after update
  apt:
    autoclean: yes
    autoremove: yes
  when:
    - packaging.format == 'deb'

- name: Clean up packages after update
  shell: '{{ packaging.command }} clean -y && {{ packaging.command }} autoremove -y'
  when:
    - packaging.format == 'pkg'
