---
PERL5LIB: $VIRT_PREFIX/lib/x86_64-linux-gnu/perl/5.20.2

projects:
  - libosinfo
  - libvirt
  - libvirt-glib
  - libvirt-go
  - libvirt-go-xml
  - libvirt-perl
  - libvirt-python
  - libvirt-tck
  - osinfo-db-tools
  - virt-viewer
