---
packages:
  - apparmor
  - augeas
  - augeas-lenses
  - avahi
  - bash-completion
  - ccache
  - clang
  - cppi
  - cyrus-sasl
  - device-mapper
  - diffutils
  - dlfcn
  - dnsmasq
  - dtrace
  - dwarves
  - ebtables
  - firewalld-filesystem
  - flake8
  - fuse
  - gcc
  - gettext
  - glib2
  - glibc
  - glusterfs
  - gnutls
  - ip
  - iptables
  - iscsiadm
  - libacl
  - libattr
  - libaudit
  - libblkid
  - libcap-ng
  - libcurl
  - libdbus
  - libiscsi
  - libnl3
  - libnlroute3
  - libnuma
  - libparted
  - libpcap
  - libpciaccess
  - libprlsdk
  - librbd
  - libselinux
  - libssh
  - libssh2
  - libtirpc
  - libudev
  - libxml2
  - lvm2
  - make
  - meson
  - modprobe
  - ninja
  - netcf
  - numad
  - openwsman
  - parted
  - perl
  - pkg-config
  - polkit
  - portablexdr
  - python3
  - python3-docutils
  - qemu-img
  - radvd
  - readline
  - rpcgen
  - rpmbuild
  - sanlock
  - scrub
  - sheepdog
  - showmount
  - tc
  - wireshark
  - xen
  - xfsprogs
  - xmllint
  - xsltproc
  - yajl
  - zfs
