---
packages:
  - glib2
  - glibc-static
  - gobject-introspection
  - gtk-doc
  - libcap-ng
  - liblzma
  - liblzma-static
  - libselinux
  - libtirpc
  - libxml2
  - rpcgen
  - zlib
  - zlib-static
