---
ansible_python_interpreter: /usr/local/bin/python2

PERL5LIB: $VIRT_PREFIX/lib/perl5/site_perl/mach/5.26
PYTHONPATH: $VIRT_PREFIX/lib/python3.6/site-packages

bash: /usr/local/bin/bash
java: /usr/local/bin/java
su: /usr/bin/su
sudoers: /usr/local/etc/sudoers

projects:
  - libosinfo
  - libvirt
  - libvirt-glib
  - libvirt-go
  - libvirt-go-xml
  - libvirt-perl
  - libvirt-python
  - libvirt-tck
  - osinfo-db
  - osinfo-db-tools
  - virt-manager
  - virt-viewer
