---
- hosts: all
  remote_user: root
  gather_facts: no

  tasks:

    # Bootstrap Ansible itself
    - include: 'tasks/bootstrap.yml'

- hosts: all
  remote_user: root

  vars_files:
    - '{{ base }}/vars/mappings.yml'

  tasks:

    # Prepare environment. None of the actions performed here might
    # depend on packages being installed
    - include: 'tasks/base.yml'

    # Install base packages
    - include: 'tasks/packages.yml'
      loop:
        - base
        - developer
        - perl-cpan
        - python-pip
        - vm
      loop_control:
        loop_var: project

    # Remove unwanted packages
    - include: 'tasks/packages.yml'
      vars:
        project: unwanted
        state: absent

    # Install build dependencies for each project
    - include: 'tasks/packages.yml'
      loop:
        '{{ selected_projects }}'
      loop_control:
        loop_var: project

    # Install packages needed for enabling cloud-init
    - include: 'tasks/packages.yml'
      vars:
        project: cloud-init
      when:
        - install.cloud_init

    # Configure environment. Needs to happen after installing packages
    - include: 'tasks/kludges.yml'
    - include: 'tasks/services.yml'
    - include: 'tasks/global.yml'
    - include: 'tasks/users.yml'

    # The following should only run on locally installed VMs
    - block:
      - include: 'tasks/bootloader.yml'
      - include: 'tasks/hostname.yml'
      when:
        - fully_managed | default(False)

    # Install the Gitlab runner agent
    - include: 'tasks/gitlab.yml'
      when:
        - install.flavor == 'gitlab'

    # Configure cloud-init
    - include: 'tasks/cloud-init.yml'
      when:
        - install.cloud_init
