---
- hosts: all
  remote_user: root
  gather_facts: no

  tasks:

    # Bootstrap Ansible itself
    - include: '{{ playbook_base }}/tasks/bootstrap.yml'

- hosts: all
  remote_user: root

  vars_files:
    - '{{ base }}/vars/mappings.yml'

  tasks:

    # Prepare environment. None of the actions performed here might
    # depend on packages being installed
    - include: '{{ playbook_base }}/tasks/base.yml'

    # Install base packages
    - include: '{{ playbook_base }}/tasks/packages.yml'
      loop:
        - base
        - developer
      loop_control:
        loop_var: project

    # Remove unwanted packages
    - include: '{{ playbook_base }}/tasks/packages.yml'
      vars:
        project: unwanted
        state: absent

    # Install build dependencies for each project
    - include: '{{ playbook_base }}/tasks/packages.yml'
      loop:
        '{{ selected_projects }}'
      loop_control:
        loop_var: project

    # Install packages needed for enabling cloud-init
    - include: '{{ playbook_base }}/tasks/packages.yml'
      vars:
        project: cloud-init
      when:
        - install.cloud_init

    # Configure environment. Needs to happen after installing packages
    - include: '{{ playbook_base }}/tasks/kludges.yml'
    - include: '{{ playbook_base }}/tasks/bootloader.yml'
    - include: '{{ playbook_base }}/tasks/services.yml'
    - include: '{{ playbook_base }}/tasks/global.yml'
    - include: '{{ playbook_base }}/tasks/users.yml'

    # Install the Gitlab runner agent
    - include: '{{ playbook_base }}/tasks/gitlab.yml'
      when:
        - install.flavor == 'gitlab'

    # Configure cloud-init
    - include: '{{ playbook_base }}/tasks/cloud-init.yml'
      when:
        - install.cloud_init
