---
PERL5LIB: $VIRT_PREFIX/lib64/perl5
PYTHONPATH: $VIRT_PREFIX/lib64/python2.7/site-packages

projects:
  - libosinfo
  - libvirt
  - libvirt-cim
  - libvirt-glib
  - libvirt-go
  - libvirt-go-xml
  - libvirt-perl
  - libvirt-python
  - libvirt-sandbox
  - osinfo-db
  - osinfo-db-tools
  - virt-viewer
