---
os:
  name: 'CentOS'
  version: '7'

packaging:
  format: rpm
  command: yum

paths:
  bash: /bin/bash
  cc: /usr/bin/gcc
  ccache: /usr/bin/ccache
  java: /usr/bin/java
  make: /usr/bin/make
  ninja: /usr/bin/ninja-build
  python: /usr/bin/python3
  su: /bin/su
  sudoers: /etc/sudoers

ansible_python_package: python2
ansible_python_interpreter: /usr/bin/python2

install:
  url: http://mirror.centos.org/centos/7/os/x86_64/

docker:
  base: centos:7
