---
packages:
  - autoconf
  - automake
  - autopoint
  - bash
  - ccache
  - cppi
  - gcc
  - gettext
  - git
  - glibc
  - libtool
  - libtoolize
  - make
  - patch
  - perl
  - pkg-config
  - rpmbuild
  - screen
  - sudo
  - vim
