---
- name: Enable fedora-rawhide-kernel-nodebug repository
  template:
    src: '{{ playbook_base }}/templates/fedora-rawhide-kernel-nodebug.repo.j2'
    dest: /etc/yum.repos.d/fedora-rawhide-kernel-nodebug.repo
    owner: root
    group: root
  when:
    - os_name == 'Fedora'
    - os_version == 'Rawhide'

- name: Enable EPEL repository
  package:
    name: epel-release
    state: latest
  when:
    - os_name == 'CentOS'
    - os_version == '7'

- name: Update installed packages
  package:
    name: '*'
    state: latest
  when:
    - package_format == 'rpm'
    - not ( os_name == 'Fedora' and
            os_version == 'Rawhide' )

- name: Update installed packages
  package:
    name: fedora-gpg-keys
    state: latest
    disable_gpg_check: yes
  when:
    - os_name == 'Fedora'
    - os_version == 'Rawhide'

- name: Update installed packages
  command: '{{ package_manager }} update --refresh --exclude "kernel*" -y'
  args:
    warn: no
  when:
    - os_name == 'Fedora'
    - os_version == 'Rawhide'

- name: Update installed packages
  command: '{{ package_manager }} update --disablerepo="*" --enablerepo=fedora-rawhide-kernel-nodebug "kernel*" -y'
  args:
    warn: no
  when:
    - os_name == 'Fedora'
    - os_version == 'Rawhide'

- name: Update installed packages
  apt:
    upgrade: dist
    update_cache: yes
  when:
    - package_format == 'deb'

- name: Update installed packages
  shell: '{{ package_manager }} update && {{ package_manager }} upgrade -y'
  args:
    warn: no
  when:
    - package_format == 'pkg'

- name: Clean up packages after update
  shell: '{{ package_manager }} clean packages -y && {{ package_manager }} autoremove -y'
  args:
    warn: no
  when:
    - package_format == 'rpm'

- name: Clean up packages after update
  apt:
    autoclean: yes
    autoremove: yes
  when:
    - package_format == 'deb'

- name: Clean up packages after update
  shell: '{{ package_manager }} clean -y && {{ package_manager }} autoremove -y'
  args:
    warn: no
  when:
    - package_format == 'pkg'

- name: Configure hostname
  hostname:
    name: '{{ inventory_hostname }}'
