---
# Default to installing packages if state is not passed from the caller
- set_fact:
    state: present
  when:
    - state is undefined

- name: '{{ project }}: Load variables'
  include_vars:
    file: '{{ base }}/vars/projects/{{ project }}.yml'

- set_fact:
    temp: {}

- name: '{{ project }}: Verify mappings'
  fail:
    msg: 'No mappings defined for {{ item }}'
  with_items:
    '{{ packages }}'
  when:
    - mappings[item] is undefined

- name: '{{ project }}: Look up mappings (default)'
  set_fact:
    temp: '{{ temp|combine({ item: mappings[item]["default"] }) }}'
  with_items:
    '{{ packages }}'
  when:
    - mappings[item]["default"] is defined

- name: '{{ project }}: Look up mappings (package format)'
  set_fact:
    temp: '{{ temp|combine({ item: mappings[item][package_format] }) }}'
  with_items:
    '{{ packages }}'
  when:
    - mappings[item][package_format] is defined

- name: '{{ project }}: Look up mappings (OS name)'
  set_fact:
    temp: '{{ temp|combine({ item: mappings[item][os_name] }) }}'
  with_items:
    '{{ packages }}'
  when:
    - mappings[item][os_name] is defined

- name: '{{ project }}: Look up mappings (OS version)'
  set_fact:
    temp: '{{ temp|combine({ item: mappings[item][os_name + os_version] }) }}'
  with_items:
    '{{ packages }}'
  when:
    - mappings[item][os_name + os_version] is defined

- name: '{{ project }}: Look up mappings (arch with default)'
  set_fact:
    temp: '{{ temp|combine({ item: mappings[item]["x86_64" + "-" + "default"] }) }}'
  with_items:
    '{{ packages }}'
  when:
    - mappings[item]["x86_64" + "-" + "default"] is defined

- name: '{{ project }}: Look up mappings (arch with package format)'
  set_fact:
    temp: '{{ temp|combine({ item: mappings[item]["x86_64" + "-" + package_format] }) }}'
  with_items:
    '{{ packages }}'
  when:
    - mappings[item]["x86_64" + "-" + package_format] is defined

- name: '{{ project }}: Look up mappings (arch with OS name)'
  set_fact:
    temp: '{{ temp|combine({ item: mappings[item]["x86_64" + "-" + os_name] }) }}'
  with_items:
    '{{ packages }}'
  when:
    - mappings[item]["x86_64" + "-" + os_name] is defined

- name: '{{ project }}: Look up mappings (arch with OS version)'
  set_fact:
    temp: '{{ temp|combine({ item: mappings[item]["x86_64" + "-" + os_name + os_version] }) }}'
  with_items:
    '{{ packages }}'
  when:
    - mappings[item]["x86_64" + "-" + os_name + os_version] is defined

- set_fact:
    flattened: []

- name: '{{ project }}: Flatten package list'
  set_fact:
    flattened: '{{ flattened }} + [ "{{ temp[item] }}" ]'
  with_items:
    '{{ temp }}'
  when:
    - temp[item] != None
    - temp[item] not in flattened

- name: '{{ project }}: Install/remove packages (state={{ state }})'
  package:
    name: '{{ flattened|sort }}'
    state: '{{ state }}'

- set_fact:
    pip_temp: {}

- name: '{{ project }}: Verify pip mappings'
  fail:
    msg: 'No mappings defined for {{ item }}'
  with_items:
    '{{ packages }}'
  when:
    - mappings[item] is undefined
    - pip_mappings[item] is undefined

- name: '{{ project }}: Look up pip mappings (default)'
  set_fact:
    pip_temp: '{{ pip_temp|combine({ item: pip_mappings[item]["default"] }) }}'
  with_items:
    '{{ packages }}'
  when:
    - pip_mappings[item]["default"] is defined

- set_fact:
    pip_flattened: []

- name: '{{ project }}: Flatten pip package list'
  set_fact:
    pip_flattened: '{{ pip_flattened }} + [ "{{ pip_temp[item] }}" ]'
  with_items:
    '{{ pip_temp }}'
  when:
    - pip_temp[item] != None
    - pip_temp[item] not in pip_flattened

- name: '{{ project }}: Install packages from pip (state={{ state }})'
  pip:
    name: '{{ pip_flattened|sort }}'
    executable: pip3
    state: '{{ state }}'
  with_items:
    '{{ packages }}'
  when:
    - temp[item] is defined
    - temp[item] == None
    - pip_temp[item] is defined
    - pip_temp[item] != None
