---
- set_fact:
    commands: {}
    files: {}

- name: 'Look for commands'
  shell: 'which {{ item }} 2>/dev/null || true'
  register: which
  with_items:
    - bash
    - ccache
    - gmake
    - java
    - make
    - su

- name: 'Look for files'
  shell: 'find /etc /usr/local/etc -name {{ item }} 2>/dev/null'
  register: find
  with_items:
    - sudoers

- set_fact:
    commands: '{{ commands|combine({ item.item: item.stdout }) }}'
  no_log: True
  with_items:
    '{{ which.results }}'

- set_fact:
    files: '{{ files|combine({ item.item: item.stdout }) }}'
  no_log: True
  with_items:
    '{{ find.results }}'

- name: 'Export paths'
  set_fact:
    bash: '{{ commands["bash"] }}'
    ccache: '{{ commands["ccache"] }}'
    java: '{{ commands["java"] }}'
    su: '{{ commands["su"] }}'
    sudoers: '{{ files["sudoers"] }}'

# Prefer gmake, fall back to make
- name: 'Export paths'
  set_fact:
    make: '{{ commands["gmake"] }}'
  when:
    - commands["gmake"] != ''

- name: 'Export paths'
  set_fact:
    make: '{{ commands["make"] }}'
  when:
    - make is undefined
