---
- name: 'root: Set password'
  user:
    name: root
    password: '{{ lookup("file", root_password_file)|password_hash("sha512") }}'
    shell: '{{ bash }}'

- name: 'root: Configure ssh access'
  authorized_key:
    user: root
    key: '{{ lookup("file", lookup("env", "HOME") + "/.ssh/id_rsa.pub") }}'
    state: present

- name: 'root: Disable ssh password authentication'
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^#*\s*PermitRootLogin\s*.*$'
    line: 'PermitRootLogin without-password'
    state: present

- name: '{{ flavor }}: Create group'
  group:
    name: '{{ flavor }}'
    state: present

- name: '{{ flavor }}: Create user account'
  user:
    name: '{{ flavor }}'
    group: '{{ flavor }}'
    comment: '{{ flavor }}'
    password: '*'
    shell: '{{ bash }}'

- name: '{{ flavor }}: Set password'
  user:
    name: '{{ flavor }}'
    password: '{{ "test"|password_hash("sha512") }}'
  when:
    - flavor == 'test'

- name: '{{ flavor }}: Configure ssh access'
  authorized_key:
    user: '{{ flavor }}'
    key: '{{ lookup("file", lookup("env", "HOME") + "/.ssh/id_rsa.pub") }}'
    state: present

- name: '{{ flavor }}: Grant passwordless sudo access'
  lineinfile:
    path: '{{ sudoers }}'
    line: '{{ flavor }} ALL=(ALL) NOPASSWD: ALL'
    state: present
    validate: 'visudo -cf %s'
  when:
    - flavor == 'test'

- name: '{{ flavor }}: Configure ccache'
  file:
    path: /home/{{ flavor }}/.{{ item }}
    state: directory
    owner: '{{ flavor }}'
    group: '{{ flavor }}'
  with_items:
    - ccache
    - ccache/bin

- name: '{{ flavor }}: Configure ccache'
  template:
    src: '{{ playbook_base }}/templates/ccache.conf.j2'
    dest: /home/{{ flavor }}/.ccache/ccache.conf
    owner: '{{ flavor }}'
    group: '{{ flavor }}'

- name: '{{ flavor }}: Create ccache wrappers'
  file:
    src: '{{ ccache }}'
    dest: /home/{{ flavor }}/.ccache/bin/{{ item }}
    state: link
    owner: '{{ flavor }}'
    group: '{{ flavor }}'
  with_items:
    - cc
    - clang
  when:
    - ccache != ''
    - os_name == 'FreeBSD'

- name: '{{ flavor }}: Create ccache wrappers'
  file:
    src: '{{ ccache }}'
    dest: /home/{{ flavor }}/.ccache/bin/{{ item }}
    state: link
    owner: '{{ flavor }}'
    group: '{{ flavor }}'
  with_items:
    - cc
    - gcc
  when:
    - ccache != ''
    - os_name != 'FreeBSD'

- name: '{{ flavor }}: Create shell profile'
  template:
    src: '{{ playbook_base }}/templates/{{ item }}.j2'
    dest: /home/{{ flavor }}/.{{ item }}
    owner: '{{ flavor }}'
    group: '{{ flavor }}'
  with_items:
    - bash_profile
    - bashrc

- name: '{{ flavor }}: Remove existing shell profile'
  file:
    path: /home/{{ flavor }}/.{{ item }}
    state: absent
  with_items:
    - profile
