---
ansible_python_interpreter: /usr/local/bin/python2

PERL5LIB: $VIRT_PREFIX/lib/perl5/amd64-freebsd-thread-multi
PYTHONPATH: $VIRT_PREFIX/lib/python3.6/site-packages

projects:
  - libosinfo
  - libvirt
  - libvirt-dbus
  - libvirt-glib
  - libvirt-go
  - libvirt-go-xml
  - libvirt-perl
  - libvirt-python
  - libvirt-tck
  - osinfo-db
  - osinfo-db-tools
  - virt-manager
  - virt-viewer
