---
os:
  name: 'CentOS'
  version: '7'

packaging:
  format: rpm
  command: yum

paths:
  bash: /bin/bash
  cc: /usr/bin/gcc
  ccache: /usr/bin/ccache
  make: /usr/bin/make
  ninja: /usr/bin/ninja-build
  pip3: /usr/bin/pip3
  python: /usr/bin/python3
  sudoers: /etc/sudoers

ansible_python_package: python2
ansible_python_interpreter: /usr/bin/python2

install:
  url: http://mirror.centos.org/centos/7/os/x86_64/

containers:
  base: docker.io/library/centos:7
