---
- name: Bootstrap the package module
  command: apt-get install -y python-apt
  args:
    creates: /usr/lib/python2*/*-packages/apt
    warn: no
  when:
    - package_format == 'deb'

- name: Bootstrap the package module
  command: dnf install -y python2-dnf
  args:
    creates: /usr/lib*/python2*/*-packages/dnf
    warn: no
  when:
    - os_name == 'Fedora'

- name: Permit file editing on SELinux-enabled systems
  package:
    name: libselinux-python
    state: present
  when:
    - ( os_name == 'CentOS' or
        os_name == 'Fedora' )

- name: Enable jessie-backports repository
  template:
    src: templates/jessie-backports.sources.j2
    dest: /etc/apt/sources.list.d/jessie-backports.list
    owner: root
    group: root
  when:
    - os_name == 'Debian'
    - os_version == '8'
    - flavor == 'jenkins'

- name: Configure APT pinning for jessie-backports
  template:
    src: templates/jessie-backports.preferences.j2
    dest: /etc/apt/preferences.d/jessie-backports
    owner: root
    group: root
  when:
    - os_name == 'Debian'
    - os_version == '8'
    - flavor == 'jenkins'

- name: Enable fedora-rawhide-kernel-nodebug repository
  template:
    src: templates/fedora-rawhide-kernel-nodebug.repo.j2
    dest: /etc/yum.repos.d/fedora-rawhide-kernel-nodebug.repo
    owner: root
    group: root
  when:
    - os_name == 'Fedora'
    - os_version == 'Rawhide'

- name: Update installed packages
  package:
    name: '*'
    state: latest
  when:
    - package_format == 'rpm'
    - not ( os_name == 'Fedora' and
            os_version == 'Rawhide' )

- name: Update installed packages
  command: dnf update --refresh --exclude 'kernel*' -y
  args:
    warn: no
  when:
    - os_name == 'Fedora'
    - os_version == 'Rawhide'

- name: Update installed packages
  command: dnf update --disablerepo='*' --enablerepo=fedora-rawhide-kernel-nodebug 'kernel*' -y
  args:
    warn: no
  when:
    - os_name == 'Fedora'
    - os_version == 'Rawhide'

- name: Update installed packages
  apt:
    upgrade: dist
    update_cache: yes
  when:
    - package_format == 'deb'

- name: Update installed packages
  shell: pkg update && pkg upgrade -y
  when:
    - package_format == 'pkg'

- name: Clean up packages after update
  command: yum clean packages -y
  args:
    warn: no
  when:
    - package_format == 'rpm'

- name: Clean up packages after update
  command: yum autoremove -y
  args:
    warn: no
  when:
    - package_format == 'rpm'

- name: Clean up packages after update
  apt:
    autoclean: yes
    autoremove: yes
  when:
    - package_format == 'deb'

- name: Clean up packages after update
  shell: pkg clean -y && pkg autoremove -y
  when:
    - package_format == 'pkg'

- name: Configure hostname
  hostname:
    name: '{{ inventory_hostname }}'
