---
# libvirt can't detect these automatically at the moment, so a kludge
# is required. Can be dropped it as soon as libvirt has been fixed
- name: Create compatibility symlinks
  file:
    src: '/usr/local/{{ item }}'
    dest: '/usr/{{ item }}'
    state: link
    force: yes
  with_items:
    - include/sasl
    - include/yajl
    - lib/libsasl2.so
    - lib/libyajl.so
  when:
    - os_name == 'FreeBSD'

# Same as above, except we only need to do it on FreeBSD 11 because
# FreeBSD 10 shipped (an old version of) readline in the base system
- name: Create compatibility symlinks
  file:
    src: '/usr/local/{{ item }}'
    dest: '/usr/{{ item }}'
    state: link
    force: yes
  with_items:
    - include/readline
    - lib/libreadline.so
  when:
    - os_name == 'FreeBSD'
    - os_version == '11'

# FreeBSD compiles bash without defining SSH_SOURCE_BASHRC, which means
# it won't try to detect when it's spawned by ssh and source ~/.bashrc
# when that's the case. Our workaround is setting $BASH_ENV globally
- name: Enable ~/.bashrc
  replace:
    path: /etc/login.conf
    regexp: '^(.*):setenv=(BASH_ENV=[^,]*,)?(.*):\\$'
    replace: '\1:setenv=BASH_ENV=~/.bashrc,\3:\\'
  register: loginconf
  when:
    - os_name == 'FreeBSD'

- name: Enable ~/.bashrc
  command: cap_mkdb /etc/login.conf
  when:
    - loginconf.changed

# FreeBSD switched to Perl 5.26, which makes a long existing warning in
# intltool-update turn into an error and causes jobs to fail. While we
# wait for the port to be fixed, we can patch things up ourselves.
#
# See https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=227444
- name: Look for intltool-update
  stat:
    path: /usr/local/bin/intltool-update
  register: intltoolupdate
  when:
    - os_name == 'FreeBSD'

- name: Fix intltool-update
  replace:
    path: /usr/local/bin/intltool-update
    regexp: '^(.*) !~ /\\\$\{\?\$2\}\?/;$'
    replace: '\1 !~ /\\$\\{?$2}?/;'
  when:
    - os_name == 'FreeBSD'
    - intltoolupdate.stat.exists
